### ISSUE TITLE
The database created is void

### ISSUE THREAD

**Issue by sailormoon-c** [amulog/amulog#1]
I followed your instruction and I changed your config file test.conf general.src_path to the location of my log file which is "BGL.log". However, when I ran "python -m amulog show-db-info -c test.conf", I got no output and "ValueError: No data found in DB". Please could you tell me how to handle this bug?

**Comment by cpflat** [comment]
Are there any (non-empty) file in the filepath of "database.sqlite3_filename"?
If not, you need to generete DB before show-db-info with the following command:
    $ python -m amulog db-make -c test.conf
This command may take a little long because this step is the main part of amulog (preprocessing and classifying log messages).

**Comment by cpflat** [comment]
The logdag tutorial (including amulog DB generation) may help you understand the usage.
https://github.com/amulog/logdag/tree/master/tutorial

**Comment by sailormoon-c** [comment]
> 

I found two files which are log.db(44KB) and lt_fail(1.4GB) but the database is empty I think. I will try the tutorial first and come back later if there is any other problems. Thanks so much for your kind reply.

**Comment by sailormoon-c** [comment]
> python -m amulog db-make -c test.conf

I just re-enter this command and it ran for a while, however, the error still remains.

**Comment by cpflat** [comment]
It means you fail to parse  any of the input log data, so the database is empty.
If you want to analyze log data without standard syslog format,
you need to specify a log2seq parser script in "manager.parser_script".

There are sample parser files in the following url, which includes BGL.
https://github.com/amulog/log2seq/tree/master/example

**Comment by sailormoon-c** [comment]
> It means you fail to parse any of the input log data, so the database is empty. If you want to analyze log data without standard syslog output format, you need to specify a log2seq parser script in "manager.parser_script".
> 
> There are sample parser files in the following url, which includes BGL. https://github.com/amulog/log2seq/tree/master/example

I have downloaded the log parser file for BGL and re-run the command line "python -m amulog db-make -c test.conf". The details of my test.conf file are as follows:

**Comment by cpflat** [comment]
It seems I need to check the code.
I wll try it with BGL_2k.log.
Unfortunately, it would NOT be in a few days due to my business...

**Comment by sailormoon-c** [comment]
> It seems I need to check the code. I wll try it with BGL_2k.log. Unfortunately, it would NOT be in a few days due to my business...

Oh thank you so much. I just utilised the raw BGL.log and it cannot generate the database correctly. Could you please check it as soon as possible? I kindly want to cite your paper for the upcoming conference ICPADS 2023 the submission deadline is 31st August and I am struggling with my PhD dissertation about log-based root cause analysis. I am really impressed by your work which is highly related to my research topic and I plan to utilise HDFS, BGL and some other classical public log datasets and enhance the results based on improved PC algorithm.
I will appreciate if you can turn to me as soon as possible and Thanks so much for your patience and help.

**Comment by sailormoon-c** [comment]
When I transferred to HDFS raw logs which are downloaded from LogHub, I still got errors (I have already downloaded the parser.py file for HDFS logs) when running "amulog db-make -c hdfs_amulog.conf".
My config file for HDFS is<
[general]
 src_path = HDFS.log
 src_recur = false
 logging = hdfs.log
 [database]
 database = sqlite3
 sqlite3_filename = hdfs.db
 [manager]
 indata_filename = hdfs.dump
 parser_script = hdfs_parser.py
 fail_output = hdfs_fail.txt
 [log_template]
 lt_methods = drain
 sym_ignore = true
 [log_template_import]
 def_path = hdfs_lt.txt
 [visual]
tag_method = dummy
>
However I ended up with an error trace as follows:
Traceback (most recent call last):
  File "/home/jin/.local/bin/amulog", line 8, in <module>
    sys.exit(main())
  File "/home/jin/.local/lib/python3.8/site-packages/amulog/__main__.py", line 631, in main
    cli.main(DICT_ARGSET, ALIASES, SUBLIB)
  File "/home/jin/.local/lib/python3.8/site-packages/amulog/cli.py", line 60, in main
    func(ns)
  File "/home/jin/.local/lib/python3.8/site-packages/amulog/__main__.py", line 109, in db_make
    manager.process_files_online(conf, targets, True)
  File "/home/jin/.local/lib/python3.8/site-packages/amulog/manager.py", line 542, in process_files_online
    ltm.process_line(line)
  File "/home/jin/.local/lib/python3.8/site-packages/amulog/manager.py", line 193, in process_line
    pline = self.get_parsed_line(line)
  File "/home/jin/.local/lib/python3.8/site-packages/amulog/manager.py", line 189, in get_parsed_line
    pline = normalize_pline(pline, self._ha, self._drop_undefhost)
  File "/home/jin/.local/lib/python3.8/site-packages/amulog/manager.py", line 460, in normalize_pline
    org_host = pline["host"]
KeyError: 'host'
I think the code may need to be checked and updated because it cannot be run properly. Thank you!

**Comment by cpflat** [comment]
New amulog version v0.3.10 is released.
It just ignore log lines of parse failures more reliably.
Unfortunately, I cannot test it with the full datasets because I do not have access to them now.

**Comment by sailormoon-c** [comment]
Hi, I successfully parsed BGL dataset with the latest version of amulog. However, when I followed your tutorial of logdag to generate DAGs to do root cause analysis, there is still an error when I ran " python -m logdag.source make-evdb-log-all -c bgl_logdag.conf", the details of the error is as follows<
(amulog) jin@jed-B365-HD3:~/zyj/amulog$ python -m logdag.source make-evdb-log-all -c bgl_logdag.conf
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/jin/zyj/amulog/logdag/logdag/source/__main__.py", line 217, in <module>
    main()
  File "/home/jin/zyj/amulog/logdag/logdag/source/__main__.py", line 213, in main
    cli.main(DICT_ARGSET)
  File "/home/jin/.local/lib/python3.8/site-packages/amulog/cli.py", line 60, in main
    func(ns)
  File "/home/jin/zyj/amulog/logdag/logdag/source/__main__.py", line 36, in make_evdb_log_all
    w_term = config.getterm(conf, "general", "evdb_whole_term")
  File "/home/jin/.local/lib/python3.8/site-packages/amulog/config.py", line 132, in getterm
    dt = datetime.datetime.strptime(e.strip(), "%Y-%m-%d %H:%M:%S")
  File "/usr/lib/python3.8/_strptime.py", line 568, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
  File "/usr/lib/python3.8/_strptime.py", line 352, in _strptime
    raise ValueError("unconverted data remains: %s" %
ValueError: unconverted data remains: 
> 
And the details of my config file "bgl_logdag.conf" is:
<
[general]
# change datetime range corresponding to your data
evdb_whole_term = 2005-06-04 00:00:00, 2006-01-04 00:00:00
 evdb_unit_term = 24h
 evdb_unit_diff = 24h
 evdb_binsize = 1m
 logging = bgl_logdag.log
 log_source = amulog
 evdb = sql 

[database_amulog]
 source_conf = test.conf
 event_gid = ltid

[database_sql]
 database = sqlite3
 sqlite3_filename = bgl_logdag.db
 
[filter]
 rules = sizetest, filter_periodic, remove_linear
 pre_count = 5
 pre_term = 6h
 fourier_sample_rule = 1d_10s, 7d_1m 
 fourier_th_spec = 0.4
 fourier_th_eval = 0.1
 fourier_th_restore = 0.5
 fourier_peak_order = 200 
 linear_sample_rule = 1d_10s
 linear_count = 10
 linear_th = 0.5
 corr_sample_rule = 1d_10s
 corr_th = 0.5
 corr_diff = 1h, 1d
 
[dag]
# change datetime range corresponding to your data change datetime range corresponding to your data
 whole_term = 2005-06-04 00:00:00, 2006-01-04 00:00:00
 source = log
 area = all
 unit_term = 24h
 unit_diff = 24h
 ci_bin_method = sequential
 ci_bin_size = 1m
 ci_bin_diff = 1m
 ci_func = gsq
 cause_algorithm = pc
 skeleton_method = stable
 skeleton_depth = -1
 skeleton_threshold = 0.01
 skeleton_verbose = false 
 args_fn = args
 output_dir = bgl_result
 output_dag_format = json
 
 [prior_knowledge]
 methods =
 >
Thank you so much for your kind help!!! :) I was stuck again

**Comment by cpflat** [comment]
It works for BGL_2k.log on my environment without the error .
The error message says that it fails on parsing general.evdb_whole_term,
which is weird for me because the format looks same with my config.
It seems your configuration issue, but I have no idea to debug it remotely.

You should check variables on the processing.
For example, you can insert print functions in the installed scripts.
(The installed scripts can be found in the error message or with "pip show" command.)
Check related variables near
"File "/home/jin/zyj/amulog/logdag/logdag/source/main.py", line 36, in make_evdb_log_all"
 or "File "/home/jin/.local/lib/python3.8/site-packages/amulog/config.py", line 132, in getterm".
It may help you to detect what is wrong on the configuration.
