### ISSUE TITLE
Problem with enabling parallel processing for offline mode 

### ISSUE THREAD

**Issue by raszuk** [amulog/amulog#3]
Hi, 

When I am trying to enable parallel processing on directory of log files in offline mode with "-p" switch I am getting errors: 

(.venv) robert@web-arc-lab:~/arclog/.log_out/test_upf_leaf1/amulog_run$ time python -m amulog db-make -c test.conf -p
Process ForkPoolWorker-1:
Traceback (most recent call last):
  File "/usr/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.10/multiprocessing/pool.py", line 109, in worker
    initializer(*initargs)
  File "/home/robert/arclog/.venv/lib/python3.10/site-packages/amulog/manager.py", line 84, in _init_pool
    assert not ltgen.is_stateful(), \
AssertionError: parallel processing is limited to stateless methods
Process ForkPoolWorker-2:
Process ForkPoolWorker-3:
Traceback (most recent call last):
  File "/usr/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.10/multiprocessing/pool.py", line 109, in worker
    initializer(*initargs)
  File "/home/robert/arclog/.venv/lib/python3.10/site-packages/amulog/manager.py", line 84, in _init_pool
    assert not ltgen.is_stateful(), \
AssertionError: parallel processing is limited to stateless methods
Process ForkPoolWorker-4:
Traceback (most recent call last):
  File "/usr/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.10/multiprocessing/pool.py", line 109, in worker
    initializer(*initargs)
  File "/home/robert/arclog/.venv/lib/python3.10/site-packages/amulog/manager.py", line 84, in _init_pool
    assert not ltgen.is_stateful(), \
AssertionError: parallel processing is limited to stateless methods
Traceback (most recent call last):
  File "/usr/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.10/multiprocessing/pool.py", line 109, in worker
    initializer(*initargs)
  File "/home/robert/arclog/.venv/lib/python3.10/site-packages/amulog/manager.py", line 84, in _init_pool
    assert not ltgen.is_stateful(), \
AssertionError: parallel processing is limited to stateless methods
Process ForkPoolWorker-5:
Process ForkPoolWorker-6:
Traceback (most recent call last):
  File "/usr/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.10/multiprocessing/pool.py", line 109, in worker
    initializer(*initargs)
  File "/home/robert/arclog/.venv/lib/python3.10/site-packages/amulog/manager.py", line 84, in _init_pool

Is this supposed to work ? 

If not what are alternative options where I can create a database from multiple log files in parallel ? 

Many many thx,
Robert

**Comment by raszuk** [comment]
Is this that I am using drain lt_method and I should be using different one(s) like RegEx or CRF ?

**Comment by cpflat** [comment]
Amulog's parallel processing is a very simple approach, just processing multiple lines in parallel.
Therefore, the parallel processing is currently available only for "Stateless" lt_methods, the methods in which the result is the same regardless of the order of the inputs.
These methods should inherit lt_common.LTGenStateless (e.g., RegEx or CRF).

Drain basically depends on the order of input, so amulog does not support parallel processing for Drain.
I understand that there is a paper to extend Drain for parallel processing, but at least not yet integrated into amulog.

**Comment by raszuk** [comment]
Hi, 

> Amulog's parallel processing is a very simple approach, just processing multiple lines in parallel.

I was actually looking for a way to do parallel processing on different log files to the same database .. not about processing multiple lines in parallel from the same log file. 

I tried to call amulog with nohup and & but the db get's messed-up. 

Assume I have 200 log files and using amulog in recursive directory mode - what would be the recommended way to process not 1 file at a time but as many as available CPU cores ? 

Many thx,
R.

PS. I found that for my data the algorithm which works best and fastest is: **va**

**Comment by cpflat** [comment]
The problem is same even when the parallel processing is not per-line but per file.
We cannot process a file with the information obtained from another file in this parallel processing feature.

If you can sacrifice real-time performance or coverage, following workflow can be a candidate.
1. Create templates on serial processing from some files (e.g., with Drain) on a test db and export the estimated templates.
2. Process all files with "import" method using the exported templates on a production db ("import" is Stateless, so parallel processing is available). In this step, logs with unknown templates (not in the estimated templates in step 1) are ignored. If you do not care the coverage, the processing is over.
3. Add the ignored logs recorded in lt_fail.log into the input of step 1, and you can update the template lists by step 1 again.
4. Update the production db by resuming (db-add) step 3 with updated exported templates (input is lt_fail.log).

This approach is effective if log templates in your data are not very diverse.

If you try high-level parallel processing, the next problem would be SQlite: it does not allow simultaneous write transaction.
Amulog has a different option using MySQL, but this feature has not been updated for about 8 years...
