### ISSUE TITLE
dlog method produces errors and does not run 

### ISSUE THREAD

**Issue by raszuk** [amulog/amulog#4]
(.venv) robert@DESKTOP-FQEPVRS:~/arclog/.log_out/test_upf_leaf1/amulog_run$ time python -m amulog db-make -c test.conf
^CTraceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/mnt/d/D/DEV/logs/arclog/.venv/lib/python3.12/site-packages/amulog/__main__.py", line 635, in <module>
    main()
  File "/mnt/d/D/DEV/logs/arclog/.venv/lib/python3.12/site-packages/amulog/__main__.py", line 631, in main
    cli.main(DICT_ARGSET, ALIASES, SUBLIB)
  File "/mnt/d/D/DEV/logs/arclog/.venv/lib/python3.12/site-packages/amulog/cli.py", line 60, in main
    func(ns)
  File "/mnt/d/D/DEV/logs/arclog/.venv/lib/python3.12/site-packages/amulog/__main__.py", line 111, in db_make
    manager.process_files_offline(conf, targets, True, ns.parallel)
  File "/mnt/d/D/DEV/logs/arclog/.venv/lib/python3.12/site-packages/amulog/manager.py", line 586, in process_files_offline
    ltm.process_offline(l_line)
  File "/mnt/d/D/DEV/logs/arclog/.venv/lib/python3.12/site-packages/amulog/manager.py", line 155, in process_offline
    d_pline, d_tid = self._process_offline_single(list_lines)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/d/D/DEV/logs/arclog/.venv/lib/python3.12/site-packages/amulog/manager.py", line 150, in _process_offline_single
    d_tid = self._ltgen.process_offline(offline_input)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/d/D/DEV/logs/arclog/.venv/lib/python3.12/site-packages/amulog/alg/dlog/dlog.py", line 128, in process_offline
    self._aggregate_tree(self._root)
  File "/mnt/d/D/DEV/logs/arclog/.venv/lib/python3.12/site-packages/amulog/alg/dlog/dlog.py", line 84, in _aggregate_tree
    d_cnt += cls._aggregate_tree(child)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/d/D/DEV/logs/arclog/.venv/lib/python3.12/site-packages/amulog/alg/dlog/dlog.py", line 84, in _aggregate_tree
    d_cnt += cls._aggregate_tree(child)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/d/D/DEV/logs/arclog/.venv/lib/python3.12/site-packages/amulog/alg/dlog/dlog.py", line 84, in _aggregate_tree
    d_cnt += cls._aggregate_tree(child)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/d/D/DEV/logs/arclog/.venv/lib/python3.12/site-packages/amulog/alg/dlog/dlog.py", line 93, in _aggregate_tree
    cls._merge_subtree(node, new_node)
  File "/mnt/d/D/DEV/logs/arclog/.venv/lib/python3.12/site-packages/amulog/alg/dlog/dlog.py", line 75, in _merge_subtree
    cls._merge_subtree(child, new_node)
  File "/mnt/d/D/DEV/logs/arclog/.venv/lib/python3.12/site-packages/amulog/alg/dlog/dlog.py", line 75, in _merge_subtree
    cls._merge_subtree(child, new_node)
  File "/mnt/d/D/DEV/logs/arclog/.venv/lib/python3.12/site-packages/amulog/alg/dlog/dlog.py", line 75, in _merge_subtree
    cls._merge_subtree(child, new_node)
  [Previous line repeated 13 more times]
  File "/mnt/d/D/DEV/logs/arclog/.venv/lib/python3.12/site-packages/amulog/alg/dlog/dlog.py", line 69, in _merge_subtree
    cls._merge_subtree(new_node, new_gchild)
  File "/mnt/d/D/DEV/logs/arclog/.venv/lib/python3.12/site-packages/amulog/alg/dlog/dlog.py", line 69, in _merge_subtree
    cls._merge_subtree(new_node, new_gchild)
  File "/mnt/d/D/DEV/logs/arclog/.venv/lib/python3.12/site-packages/amulog/alg/dlog/dlog.py", line 69, in _merge_subtree
    cls._merge_subtree(new_node, new_gchild)
  [Previous line repeated 9 more times]
  File "/mnt/d/D/DEV/logs/arclog/.venv/lib/python3.12/site-packages/amulog/alg/dlog/dlog.py", line 68, in _merge_subtree
    cls._merge_subtree(child, new_gchild)
  File "/mnt/d/D/DEV/logs/arclog/.venv/lib/python3.12/site-packages/amulog/alg/dlog/dlog.py", line 59, in _merge_subtree
    @classmethod

**Comment by cpflat** [comment]
I've completely forgotten how Dlog works, so it will take some time to identify the root cause.
However, at least the Dlog code has not been changed since the amulog paper (IJNM) was written, so I think that the problem depends on the input.
If possible, it would be helpful if you could provide an example of the input that causes the same problem.
