### ISSUE TITLE
logdtl method can not find 'amulog.alg.logdtl' module 

### ISSUE THREAD

**Issue by raszuk** [amulog/amulog#5]
(.venv) robert@web-arc-lab:~/arclog/.log_out/test_upf_leaf1/amulog_run$ time python -m amulog db-make -c test.conf
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/robert/arclog/.venv/lib/python3.10/site-packages/amulog/__main__.py", line 635, in <module>
    main()
  File "/home/robert/arclog/.venv/lib/python3.10/site-packages/amulog/__main__.py", line 631, in main
    cli.main(DICT_ARGSET, ALIASES, SUBLIB)
  File "/home/robert/arclog/.venv/lib/python3.10/site-packages/amulog/cli.py", line 60, in main
    func(ns)
  File "/home/robert/arclog/.venv/lib/python3.10/site-packages/amulog/__main__.py", line 109, in db_make
    manager.process_files_online(conf, targets, True)
  File "/home/robert/arclog/.venv/lib/python3.10/site-packages/amulog/manager.py", line 546, in process_files_online
    ltm = LTManager(conf, ld.db, ld.lttable, reset_db=reset_db)
  File "/home/robert/arclog/.venv/lib/python3.10/site-packages/amulog/manager.py", line 65, in __init__
    self._ltgen = init_ltgen_methods(self._conf, self._table)
  File "/home/robert/arclog/.venv/lib/python3.10/site-packages/amulog/manager.py", line 349, in init_ltgen_methods
    return init_ltgen(conf, table, lt_methods[0], shuffle)
  File "/home/robert/arclog/.venv/lib/python3.10/site-packages/amulog/manager.py", line 375, in init_ltgen
    alg_module = import_module(modname)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'amulog.alg.logdtl'

**Comment by cpflat** [comment]
Sorry, the development of logdtl on amulog has been discontinued and this is a remnant of that work.

Last year I tried to port LogDTL (https://github.com/fukuda-lab/LogDTL) to amulog, but for various reasons I had to give up.
I will clean up the invalid functions in next updates.
